// Generated by https://quicktype.io

export interface Categories {
    _embedded: Embedded;
    _links:    CategoriesLinks;
    page:      Page;
}

export interface Embedded {
    categories: Category[];
}

export interface Category {
    name:   string;
    _links: CategoryLinks;
}

export interface CategoryLinks {
    self:      Profile;
    categorie: Profile;
    activites: Profile;
}

export interface Profile {
    href: string;
}

export interface CategoriesLinks {
    self:    Profile;
    profile: Profile;
}

export interface Page {
    size:          number;
    totalElements: number;
    totalPages:    number;
    number:        number;
}
