// Generated by https://quicktype.io

export interface Creneaux {
    _embedded: Embedded;
    _links:    CreneauxLinks;
    page:      Page;
}

export interface Embedded {
    creneaus: Creneau[];
}

export interface Creneau {
    heureDebut: string;
    _links:     CreneauLinks;
}

export interface CreneauLinks {
    self:    Profile;
    creneau: Profile;
}

export interface Profile {
    href: string;
}

export interface CreneauxLinks {
    self:    Profile;
    profile: Profile;
}

export interface Page {
    size:          number;
    totalElements: number;
    totalPages:    number;
    number:        number;
}
