// Generated by https://quicktype.io

export interface Reservations {
    _embedded: Embedded;
    _links:    ReservationsLinks;
    page:      Page;
}

export interface Embedded {
    reservations: Reservation[];
}

export interface Reservation {
    nomClient:    string;
    prix:         number;
    codePaiement: number;
    reserve:      boolean;
    _links:       ReservationLinks;
}

export interface ReservationLinks {
    self:        First;
    reservation: First;
    seance:      First;
    place:       First;
}

export interface First {
    href: string;
}

export interface ReservationsLinks {
    first:   First;
    self:    First;
    next:    First;
    last:    First;
    profile: First;
}

export interface Page {
    size:          number;
    totalElements: number;
    totalPages:    number;
    number:        number;
}
